config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  namespace :users_backoffice do
    resources :tweets
    post 'tweets/:id/like', to: 'tweets#like', as: 'like_tweet'
    post 'tweets/:id/dislike', to: 'tweets#dislike', as: 'dislike_tweet'
    get 'users/timeline', to: 'users#timeline', as: 'timeline'
    put 'users/profile_update', to: 'users#update', as: 'profile_update'
    get 'users/search', to: 'users#search_for_user'
  end
  
  root to: 'users_backoffice/tweets#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user, counter_cache: true
  belongs_to :tweet
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User', counter_cache: true
  belongs_to :followed, class_name: 'User', counter_cache: true
  validates :followed_id, :follower_id, presence: true
  
  validates :folower_id, uniquiness: true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user, counter_cache: true
  has_many :likes, dependent: :destroy

  paginates_per 10

  validates :declaration, presence: true, length: { maximum: 200 }

  def like(user_id)
    self.likes.create user_id: user_id
  end

  def dislike(user_id)
    self.likes.where(user_id: user_id).first.destroy
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :likes, dependent: :destroy
  has_many :tweets, dependent: :destroy

  has_many :active_relationship, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :passive_relationship, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy

  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  paginates_per 10
  
  scope :_search_user, -> (user){ 
    where('lower(fullname) LIKE ?', "%#{user.downcase}%")
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout :layout_by_resource

  def layout_by_resource
    devise_controller? ? "#{resource_class.to_s.downcase}_devise" : 'application'
  end
  
end

app/controllers/users_backoffice/tweets_controller.rb
class UsersBackoffice::TweetsController < UsersBackofficeController
  before_action :set_tweet, only: %i[ show edit update destroy like dislike ]

  # GET /tweets or /tweets.json
  def index
    @tweets = Tweet.all.includes(:user).page(params[:page])
  end

  # GET /tweets/1 or /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets or /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user_id = current_user.id

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to users_backoffice_tweet_path(@tweet), notice: "Tweet was successfully created." }
        format.json { render users_backoffice_tweet_path(@tweet), status: :created, location: @tweet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to users_backoffice_tweet_path(@tweet), notice: "Tweet was successfully updated." }
        format.json { render users_backoffice_tweet_path(@tweet), status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet.destroy

    respond_to do |format|
      format.html { redirect_to users_backoffice_tweets_path, notice: "Tweet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def like
    @tweet.like current_user.id
    respond_to do |format|
      format.html { redirect_to users_backoffice_tweets_path, notice: 'Tweet was liked.' }
      format.json { head :no_content }
    end
  end

  def dislike
    @tweet.dislike current_user.id
    respond_to do |format|
      format.html { redirect_to users_backoffice_tweets_path, notice: 'Tweet was disliked' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:user_id, :declaration)
    end
end

app/controllers/users_backoffice/users_controller.rb
class UsersBackoffice::UsersController < UsersBackofficeController
  before_action :set_user

  def search_for_user
    if params[:user]
      @users = User._search_user(params[:user]).order(fullname: :asc).page(params[:page])
    else
      @users = User.all.order(fullname: :asc).page(params[:page])
    end
  end

  def timeline
  end

  def update
    if @user.update(user_params)
      redirect_to users_backoffice_timeline_path, notice: 'User was successfully updated'
    else
      redirect_to users_backoffice_timeline_path, alert: @user.errors
    end
  end

  private

  def set_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit(:fullname, :email)
  end
  
end

app/controllers/users_backoffice_controller.rb
class UsersBackofficeController < ApplicationController
  layout 'users_backoffice'
  before_action :authenticate_user!
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/user_backoffice_helper.rb
module UserBackofficeHelper
end

app/helpers/users_backoffice/users_helper.rb
module UsersBackoffice::UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyTwitterApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>

  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</html>

app/views/layouts/user_devise.html.erb
<!DOCTYPE html>
<html lang='pt-BR'>
  <head>
    <title>MyTwitterApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'user_devise', media: 'all', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://unpkg.com/bulmaswatch/flatly/bulmaswatch.min.css">
  </head>

  <body>

    <section class='section'>
      <div class='container' style='display:flex;justify-content:center;align-items:center;flex-direction:column;'>
        <span class='icon' style='width:128px;height:128px;font-size:128px;'>
          <i class='fa fa-twitter'></i>
        </span>

        <div class='card'>
          <div class='card-body' style='margin:50px;'>
            <%= yield %>
          </div>
        </div>
      </div>
    </section>
  </body>

  <%= javascript_pack_tag 'application' %>
  <%= javascript_pack_tag 'user_devise' %>
</html>

app/views/layouts/users_backoffice.html.erb
<!DOCTYPE html>
<html lang='pt-BR'>
  <head>
    <title>MyTwitterApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'users_backoffice', media: 'all', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://unpkg.com/bulmaswatch/flatly/bulmaswatch.min.css">
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= render 'shared/navbar' %>

    <div class='container'>
      <% flash.each do |type, message| %>
        <div class="notification is-success">
          <button class='delete'></button>
          <%= message %>
        </div>
      <% end %>
      
      <%= yield %>
    </div>

    <script>
      $(document).ready(function() {
        // Check for click events on the navbar burger icon
        $(".navbar-burger").click(function() {
            // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
            $(".navbar-burger").toggleClass("is-active");
            $(".navbar-menu").toggleClass("is-active");
        });
      });
    </script>
  </body>

  <%= javascript_pack_tag 'application' %>
  <%= javascript_pack_tag 'users_backoffice' %>
</html>

app/views/shared/_header.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="https://bulma.io">
      <%= link_to users_backoffice_tweets_path, class:'navbar-item' do %>
        <span class='icon'>
          <i class='fa fa-twitter' style='font-size:64px;'></i>
        </span>
      <% end %>
    </a>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <% unless user_signed_in? %>
            <%= link_to 'Sign up', new_user_registration_path, class: 'button is-primary is-small' %>
            <%= link_to 'Log in', new_user_session_path, class: 'button is-light is-small' %>
          <% else %>
            <%= link_to 'Log out', destroy_user_session_path(current_user), method: :delete, data: {confirm: 'Are you sure ?' }, class:"button is-danger is-small" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/shared/_navbar.html.erb
<div class="tabs is-centered">
  <ul>
    <li class="is-active">
      <a>
        <%= link_to 'Tweets', users_backoffice_tweets_path %>
      </a>
    </li>
    <li>
      <a>
        <%= link_to 'Timeline', users_backoffice_timeline_path %>
      </a>
    </li>
    <li>
      <a>
        <%= link_to 'Meet User', users_backoffice_users_search_path %>
      </a>
    </li>
  </ul>
</div>

app/views/shared/_sidebar.html.erb
<nav class="panel">
  <p class="panel-heading">
    Repositories
  </p>
  <div class="panel-block">
    <p class="control has-icons-left">
      <input class="input" type="text" placeholder="Search">
      <span class="icon is-left">
        <i class="fa fa-search" aria-hidden="true"></i>
      </span>
    </p>
  </div>
  <p class="panel-tabs">
    <a class="is-active">All</a>
    <a>Public</a>
    <a>Private</a>
  </p>
  <a class="panel-block is-active">
    <span class="panel-icon">
      <i class="fa fa-book" aria-hidden="true"></i>
    </span>
    bulma
  </a>
  <a class="panel-block">
    <span class="panel-icon">
      <i class="fa fa-book" aria-hidden="true"></i>
    </span>
    marksheet
  </a>
  <a class="panel-block">
    <span class="panel-icon">
      <i class="fa fa-book" aria-hidden="true"></i>
    </span>
    minireset.css
  </a>
  <a class="panel-block">
    <span class="panel-icon">
      <i class="fa fa-book" aria-hidden="true"></i>
    </span>
    jgthms.github.io
  </a>
  <a class="panel-block">
    <span class="panel-icon">
      <i class="fa fa-code-fork" aria-hidden="true"></i>
    </span>
    daniellowtw/infboard
  </a>
  <div class="panel-block">
    <button class="button is-link is-outlined is-fullwidth">
      Reset all filters
    </button>
  </div>
</nav>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users_backoffice/tweets/_form.html.erb
<%= form_with(model: [:users_backoffice, tweet], local: true) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% tweet.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div class='control'>
      <%= form.text_area :declaration, class:'textarea', placeholder: 'What are you thinking ?' %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit 'Publish', class:"button is-link is-small" %><br />
  </div>
<% end %>

app/views/users_backoffice/tweets/edit.html.erb
<div class='container'>
  <div class='card'>
    <div class='card-body'>
      <h1 class='title'>Editing Tweet</h1>

      <%= render 'form', tweet: @tweet %>
    </div>
  </div>
</div>

app/views/users_backoffice/tweets/index.html.erb
<div class='columns is-multiline'>
  <div class='column is-3'>
    <%= render 'shared/sidebar'%>
  </div>

  <div class='column'>
    <nav class='navbar is-transparent'>
      <div class='navbar-start'>
        <h4 class='title is-4'>Home Page</h4>
      </div>
    </nav>

    <div class='card'>
      <header class='card-header'>
        <figure class="image is-32x32">
          <%= image_tag('https://via.placeholder.com/150C/', class:'is-rounded') %>
        </figure>&nbsp;&nbsp;

        <strong><%= current_user.fullname? ? current_user.fullname : 'Sem nome' %></strong>
      </header>
      <div class='card-body'>
        <%= render 'form', tweet: Tweet.new %>
      </div>
    </div><br>

    <div class='columns is-multiline'>
      <% @tweets.each do |tweet| %>
        <div class='column is-full'>
          <div class="card">
            <header class="card-header">
              <nav class='navbar-menu is-transparent'>
                <div class='navbar-start'>
                  <figure class="image is-32x32">
                    <%= image_tag('https://via.placeholder.com/150C/', class:'is-rounded') %>
                  </figure>&nbsp;&nbsp;
                  <p class='is-size-5'>
                    <strong><%= tweet.user.fullname? ? tweet.user.fullname : 'Sem nome' %></strong>
                  </p>
                </div>
                <div class='navbar-end'>
                  <%= link_to edit_users_backoffice_tweet_path(tweet) do %>
                    <span class='icon'>
                      <i class='fa fa-pencil'></i>
                    </span>
                  <% end %> &nbsp;
                  <%= link_to users_backoffice_tweet_path(tweet), method: :delete, data: { confirm: 'Are you sure?' } do %>
                    <span class='icon'>
                      <i class='fa fa-trash'></i>
                    </span>
                  <% end %> &nbsp;
                </div>
              </nav>
            </header>
            <div class="card-content">
              <div class="content">
                <%= tweet.declaration %>
              </div>
            </div>
            <footer class="card-footer">
              <div class='btn-group'>
                <%= link_to users_backoffice_like_tweet_path(tweet), method: :post do %>
                  <span class='icon'>
                    <i class='fa fa-thumbs-up'></i>
                  </span>
                <% end %> &nbsp;
                <%= link_to users_backoffice_dislike_tweet_path(tweet), method: :post do %>
                  <span class='icon'>
                    <i class='fa fa-thumbs-down'></i>
                  </span>
                <% end %>
              </div>
            </footer>
          </div>
        </div>
      <% end %>
    </div>
    <%= paginate @tweets %>
  </div>
</div>

app/views/users_backoffice/tweets/new.html.erb
<div class='container'>
  <div class='card'>
    <div class='card-body'>
      <h1 class='title'>New Tweet</h1>

      <%= render 'form', tweet: @tweet %>
    </div>
  </div>
</div>

app/views/users_backoffice/tweets/show.html.erb
<p>
  <strong>User:</strong>
  <%= @tweet.user_id %>
</p>

<p>
  <strong>Declaration:</strong>
  <%= @tweet.declaration %>
</p>

<%= link_to 'Edit', edit_users_backoffice_tweet_path(@tweet) %> |
<%= link_to 'Back', users_backoffice_tweets_path %>

app/views/users_backoffice/users/_edit_profile.html.erb
<%= form_with model: [:users_backoffice, @user], url: users_backoffice_profile_update_path, method: :put, local: true do |f| %>
  <div class="field">
    <p class='control has-icons-left'>
      <%= f.text_field :fullname, autofocus: true, class:'input', placeholder:'Meu nome completo' %>
      <span class='icon is-small is-left'>
        <i class='fa fa-user'></i>
      </span>
    </p>
  </div>

  <div class="field">
    <p class="control has-icons-left">
      <%= f.email_field :email, autofocus: true, placeholder: "email@example.com", class:'input' %>
      <span class="icon is-small is-left">
        <i class='fa fa-envelope'></i>
      </span>
    </p>
  </div>

  <div class="field">
    <p class="control has-icons-left">
      <%= f.password_field :current_password, autocomplete: "current-password", class:'input', placeholder:'Senha atual' %>
      <span class="icon is-small is-left">
        <i class='fa fa-lock'></i>
      </span>
    </p>
  </div>

  <div class="field">
    <p class="control has-icons-left has-icons-right">
      <%= f.password_field :password, autocomplete: "new-password", class:'input', placeholder:'Confirmação de Nova Senha' %>
      <% if @minimum_password_length %>
        <br />
        <em><%= @minimum_password_length %> characters minimum</em>
      <% end %>
      <span class="icon is-small is-left">
        <i class='fa fa-lock'></i>
      </span>
    </p>
  </div>

  <div class="field">
    <p class="control has-icons-left has-icons-right">
      <%= f.password_field :password_confirmation, autocomplete: "new-password", class:'input', placeholder:'Confirmação de Nova Senha' %>
      <span class="icon is-small is-left">
        <i class='fa fa-lock'></i>
      </span>
    </p>
  </div>

  <div class="actions">
    <%= f.submit "Update", class:'button is-primary' %>
    <%= link_to "Back", users_backoffice_tweets_path, class:'button is-danger' %>
  </div>
<% end %>

app/views/users_backoffice/users/search_for_user.html.erb
<div class='columns is-multiline'>
  <div class='column is-3'>
    <%= render 'shared/sidebar'%>
  </div>

  <div class='column'>
    <nav class='navbar is-transparent'>
      <div class='navbar-start'>
        <h4 class='title is-4'>Search For User</h4>
      </div>
    </nav>

    <div class='card'>
      <header class='card-header'>
        <%= form_with url: '#', method: :get, local: true, class:'form-inline' do |form| %>
          <div class='control has-icons-left'>
            <%= form.search_field :user, class:'input is-small', placeholder:'Nome do usuário' %>
            <span class='icon is-small is-left'><i class='fa fa-search'></i></span>
          </div>
          <%= form.submit 'Pesquisar', class:'is-hidden' %>
        <% end %>
      </header>
      <div class='card-body'>
        <% @users.each do |user| %>
          <div class='card-content'>
            <div class='d-flex'>
              <figure class='image is-32x32'>
                <%= image_tag('https://via.placeholder.com/150C/', class:'is-rounded') %>
              </figure>&nbsp;
              <strong><%= user.fullname %></strong>
            </div>
          </div>
        <% end %>
      </div>
      <%= paginate @users %>
    </div>
  </div>
</div>

app/views/users_backoffice/users/timeline.html.erb
<div class='card'> <!-- Card Principal -->
  <div class='card-body'>
    
    <h2 class='title'><%= @user.fullname? ? @user.fullname : "Sem nome" %></h2>

    <div class='columns'>
      <div class='column is-3'>
        <div class='card text-center' style='display:flex;justify-content:center;align-items:center;'>
          <div class='card-body'>
            <figure class="image is-6by4" style='margin-bottom:15px;'>
              <%= image_tag('https://via.placeholder.com/150C/', class:'is-rounded') %>
            </figure>

            <h3>Cancel my account</h3>

            <p>Unhappy? <br><br><%= button_to "Cancel my account", cancel_user_registration_path(current_user), data: { confirm: "Are you sure?" }, method: :delete, class:'button is-danger' %></p>
          </div>
        </div>
      </div>
      <div class='column'>
        <h2 class='title'>My information</h2>
        <div class='card'>
          <div class='card-body'>
            <%= render 'edit_profile' %>
          </div>
        </div>
      </div>
    </div>
    <div class='columns'>
      <div class='column'>
        <div class='card text-center'>
          <header class='card-header'>
            <div class="tabs is-centered is-small is-mobile">
              <ul>
                <li class="is-active">
                  <a>
                    <span class="icon is-small"><i class="fa fa-user" aria-hidden="true"></i></span>
                    <span>Followers</span> &nbsp;(<%= @user.followed_count %>)
                  </a>
                </li>
                <li>
                  <a>
                    <span class="icon is-small"><i class="fa fa-user" aria-hidden="true"></i></span>
                    <span>Following</span> &nbsp;(<%= @user.following_count %>)
                  </a>
                </li>
                <li>
                  <a>
                    <span class="icon is-small"><i class="fa fa-comments" aria-hidden="true"></i></span>
                    <span>Last Tweets</span> &nbsp;(<%= @user.tweets_count %>)
                  </a>
                </li>
                <li>
                  <a>
                    <span class="icon is-small"><i class="fa fa-thumbs-up" aria-hidden="true"></i></span>
                    <span>Likes</span> &nbsp;(<%= @user.likes_count %>)
                  </a>
                </li>
              </ul>
            </div>
          </header>
          <div class='card-body'>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<br>